### ISSUE TITLE
Optimize for CSS

### ISSUE THREAD

**Issue by scootyboots** [vimiomori/BlueDolphin#1]
There's some strangeness I noticed in css files
![Screen Shot 2021-03-22 at 2 03 14 PM](https://user-images.githubusercontent.com/25660161/111942886-a1344c80-8b17-11eb-9240-b49bfb29abe3.png)

Notice the units px, rem, etc. are a different color from the rest of the string. Also the # in the color hex is a different color.

**Comment by vimiomori** [comment]
@scootyboots
Aah I kinda considered this a feature. Because it differentiates keywords and symbols (the semicolon`;` should be the same color as the hash`#` and colon`:` though. 

You think it's too colorful?

**Comment by scootyboots** [comment]
@vimiomori 
I guess I just haven't seen this in other themes so it feels strange to me. 

Maybe making the `;` and `:` the same color and `px, rem, etc. units` and `#` the same color. 

That way the colors are grouped based on syntactical necessity vs. special keywords/characters
